apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: my-space
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    dir /data
    appendonly yes
    save 900 1
    save 300 10
    save 60 10000

---

apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: my-space
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      nodePort: 30000
      targetPort: 6379
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: my-space
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: 'redis:6.2.5'
      command:
        - redis-server
        - /redis-conf/redis.conf
      env:
        - name: MASTER
          value: 'true'
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: '0.1'
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /redis-conf
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: redis.conf
