apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "example-app.configmap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "example-app.name" . }}
    chart: {{ template "example-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  example-config.conf: |+
    [example]
    key1 = {{ .Values.exampleConfig.key1 }}
    key2 = {{ .Values.exampleConfig.key2 }}
    key3 = {{ .Values.exampleConfig.key3 }}
    key4 = {{ .Values.exampleConfig.key4 }}