{{- range .Values.services2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" $ }}-{{ .name }}-tmp
  labels:
    {{- include "mychart.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mychart.selectorLabels" $ | nindent 4 }}
{{- end }}