apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: my-space
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat
      image: 'tomcat:9.0.53-jdk8-openjdk'
      ports:
        - containerPort: 8080
          name: http-server
