apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-chown
  namespace: kube-ops
spec:
  template:
    metadata:
      name: grafana-chown
    spec:
      containers:
      - name: grafana-chown
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["chown", "-R", "472:472", "/var/lib/grafana"]
        volumeMounts:
        - name: storage
          subPath: grafana
          mountPath: /var/lib/grafana
      restartPolicy: Never
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana