apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elk
spec:
  serviceName: ES-cluster
  replicas: 3
  selector:
    matchLabels:
      app: es-cluster
  template:
    metadata:
      name: es-cluster
      labels:
        app: es-cluster
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - sysctl
            - '-w'
            - vm.max_map_count=262144
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      containers:
        - image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.5'
          name: ES
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: my-cluster
            - name: cluster.initial_master_nodes
              value: 'ES-cluster-0,ES-cluster-1,ES-cluster-2'
            - name: discovery.seed_hosts
              value: ES-cluster
            - name: network.host
              value: _site_
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
          volumeMounts:
            - name: ES-cluster-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: ES-cluster-data
          emptyDir: {}
