apiVersion: v1
# 创建的类型为 RC 类型
kind: ReplicationController
metadata:
  # rc 名称
  name: nginx-demo
  # rc 详细信息
spec:
  # 创建的副本数
  replicas: 2
  # 标签寻择器，与 pod 的标签进行绑定
  selector:
    app: nginx-demo
  # pod 模板信息
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: Nginx-demo
          image: nginx:1.14.2
          ports:
            - containerPort: 80
