apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: my-space
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      nodePort: 30000
      targetPort: 6379
  type: NodePort