apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: my-space
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.13-2.7.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://$(hostname -f):9092,EXTERNAL://${EXTERNAL_IP:-127.0.0.1}:9094
            - name: KAFKA_LISTENERS
              value: INTERNAL://:9092,EXTERNAL://:9094
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_BROKER_ID_COMMAND
              value: "hostname | awk -F'-' '{print $NF}'"
          volumeMounts:
            - name: data
              mountPath: /kafka/data
            - name: logs
              mountPath: /kafka/logs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kafka-data
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: my-space
spec:
  ports:
    - name: external
      port: 9094
      targetPort: 9092
  selector:
    app: kafka