apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9200
    - name: tcp
      port: 9300
  selector:
    app: es-cluster
