apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: my-space
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk
