apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap4
  namespace: {{ .Release.Namespace }}
data:
  helm-configmap-example.conf: |+
    [example]
    key1 = {{ .Values.exampleConfig.key1 }}
    key2 = {{ .Values.exampleConfig.key2 }}
    key3 = {{ .Values.exampleConfig.key3 }}
    key4 = {{ .Values.exampleConfig.key4 }}
    {{ toYaml .Values.exampleConfig | indent 4 }}